### ISSUE TITLE
Add target directory

### ISSUE THREAD

**Issue by cuducos** [cuducos/chunk#13]
Once we start a download we must be able to tell the `Downloader` where to save the files. This should be passed via CLI too (e.g. in the structure described in #12) and can have a meaningful default set to the `cwd`.

**Comment by vmesel** [comment]
I'm interested on doing this!

**Comment by cuducos** [comment]
@danielfireman does it worth it to wait until #12 is covered? Or this might be tackled within #12 itself?

**Comment by vmesel** [comment]
Awesome! Roger that! Working on it! Can you assign this issue to me?
