### ISSUE TITLE
Should we export the HTTP client to make it easier for users to customize it?

### ISSUE THREAD

**Issue by cuducos** [cuducos/chunk#35]
https://github.com/cuducos/chunk/blob/53b8bf9bbc188b664d5adafe5b700e370f396886/downloader.go#L59

Just asking, I don't have any use case in mind.

Maybe someone wants to use cookies? Or authenticating before the download? Not sure. I think it's difficult because of the way we set it up: the HTTP client handles the heavy lifting of parallelism, but we might have advanced users… idk.

**Comment by danielfireman** [comment]
Great point! Sounds like a legit use case to me. Let's open it and add this clarification to its comments.
