### ISSUE TITLE
Make Chunk directory configurable

### ISSUE THREAD

**Issue by cuducos** [cuducos/chunk#39]
#38 added `~/.chunk` as the default directory for saving progress files. There's a `TODO` to make it configurable:

https://github.com/cuducos/chunk/blob/02999cdd7fd49644210e074e0e2ae3473e2af2c1/progress.go#L16-L28

Maybe reading from and environment variable like `CHUNK_DIR`?

**Comment by danielfireman** [comment]
> Maybe reading from an environment variable like `CHUNK_DIR`?

In addition, I suggest keeping it consistent with the other configuration params: `Download.ProgressTrackerDir` and a command line parameter `--progress-tracker-dir`. Or something like that.
