### ISSUE TITLE
Create the parallel download semaphore/workers limit

### ISSUE THREAD

**Issue by cuducos** [cuducos/chunk#6]
Implement a maximum of parallel downloads per domain/subdomain.
1. Identify each different subdomain in all the URLs
2. create a fixed number of channels mapped to each one `map[string]chan`
3. spin a worker reading each of these channels
4. process the download in these workers

**Comment by cuducos** [comment]
Wow! Looks awesome 💜

**Comment by danielfireman** [comment]
Awesome! This was done by https://github.com/cuducos/chunk/pull/27
